# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sumSquaredError <- function(b, y, X) {
    .Call(`_lessLM_sumSquaredError`, b, y, X)
}

sumSquaredErrorGradients <- function(b, y, X) {
    .Call(`_lessLM_sumSquaredErrorGradients`, b, y, X)
}

approximateHessian <- function(b, y, X, eps) {
    .Call(`_lessLM_approximateHessian`, b, y, X, eps)
}

elasticNet <- function(y, X, alpha, lambda) {
    .Call(`_lessLM_elasticNet`, y, X, alpha, lambda)
}

elasticNetIsta <- function(y, X, alpha, lambda) {
    .Call(`_lessLM_elasticNetIsta`, y, X, alpha, lambda)
}

scadIsta <- function(y, X, theta, lambda) {
    .Call(`_lessLM_scadIsta`, y, X, theta, lambda)
}

