# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sumSquaredError <- function(b, y, X) {
    .Call(`_lessLM_sumSquaredError`, b, y, X)
}

sumSquaredErrorGradients <- function(b, y, X) {
    .Call(`_lessLM_sumSquaredErrorGradients`, b, y, X)
}

approximateHessian <- function(b, y, X, eps) {
    .Call(`_lessLM_approximateHessian`, b, y, X, eps)
}

penalizeGlmnet <- function(y, X, startingValues, penalty, lambda, theta, initialHessian) {
    .Call(`_lessLM_penalizeGlmnet`, y, X, startingValues, penalty, lambda, theta, initialHessian)
}

penalizeIsta <- function(y, X, startingValues, penalty, lambda, theta) {
    .Call(`_lessLM_penalizeIsta`, y, X, startingValues, penalty, lambda, theta)
}

elasticNet <- function(y, X, startingValues, alpha, lambda) {
    .Call(`_lessLM_elasticNet`, y, X, startingValues, alpha, lambda)
}

elasticNetIsta <- function(y, X, startingValues, alpha, lambda) {
    .Call(`_lessLM_elasticNetIsta`, y, X, startingValues, alpha, lambda)
}

scadIsta <- function(y, X, startingValues, theta, lambda) {
    .Call(`_lessLM_scadIsta`, y, X, startingValues, theta, lambda)
}

